// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: achievements.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAchievement = `-- name: CreateAchievement :one
INSERT INTO achievements (
    code, title, description, icon, criteria_type, threshold
) VALUES (
    $1, $2, $3, $4, $5, $6
)
RETURNING id, code, title, description, icon, criteria_type, threshold, created_at, updated_at
`

type CreateAchievementParams struct {
	Code         string `json:"code"`
	Title        string `json:"title"`
	Description  string `json:"description"`
	Icon         string `json:"icon"`
	CriteriaType string `json:"criteria_type"`
	Threshold    int32  `json:"threshold"`
}

func (q *Queries) CreateAchievement(ctx context.Context, arg CreateAchievementParams) (Achievement, error) {
	row := q.db.QueryRow(ctx, createAchievement,
		arg.Code,
		arg.Title,
		arg.Description,
		arg.Icon,
		arg.CriteriaType,
		arg.Threshold,
	)
	var i Achievement
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Title,
		&i.Description,
		&i.Icon,
		&i.CriteriaType,
		&i.Threshold,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteAchievement = `-- name: DeleteAchievement :exec
DELETE FROM achievements WHERE id = $1
`

func (q *Queries) DeleteAchievement(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteAchievement, id)
	return err
}

const listAchievements = `-- name: ListAchievements :many
SELECT id, code, title, description, icon, criteria_type, threshold, created_at, updated_at FROM achievements ORDER BY threshold
`

func (q *Queries) ListAchievements(ctx context.Context) ([]Achievement, error) {
	rows, err := q.db.Query(ctx, listAchievements)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Achievement
	for rows.Next() {
		var i Achievement
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.Title,
			&i.Description,
			&i.Icon,
			&i.CriteriaType,
			&i.Threshold,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAchievement = `-- name: UpdateAchievement :one
UPDATE achievements SET
    code = $2, title = $3, description = $4, icon = $5,
    criteria_type = $6, threshold = $7, updated_at = now()
WHERE id = $1
RETURNING id, code, title, description, icon, criteria_type, threshold, created_at, updated_at
`

type UpdateAchievementParams struct {
	ID           pgtype.UUID `json:"id"`
	Code         string      `json:"code"`
	Title        string      `json:"title"`
	Description  string      `json:"description"`
	Icon         string      `json:"icon"`
	CriteriaType string      `json:"criteria_type"`
	Threshold    int32       `json:"threshold"`
}

func (q *Queries) UpdateAchievement(ctx context.Context, arg UpdateAchievementParams) (Achievement, error) {
	row := q.db.QueryRow(ctx, updateAchievement,
		arg.ID,
		arg.Code,
		arg.Title,
		arg.Description,
		arg.Icon,
		arg.CriteriaType,
		arg.Threshold,
	)
	var i Achievement
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Title,
		&i.Description,
		&i.Icon,
		&i.CriteriaType,
		&i.Threshold,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
