// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: business_claims.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createBusinessClaim = `-- name: CreateBusinessClaim :one
INSERT INTO business_claims (business_id, user_id, message)
VALUES ($1, $2, $3)
RETURNING id, business_id, user_id, message, status, created_at, resolved_at
`

type CreateBusinessClaimParams struct {
	BusinessID pgtype.UUID `json:"business_id"`
	UserID     pgtype.UUID `json:"user_id"`
	Message    *string     `json:"message"`
}

func (q *Queries) CreateBusinessClaim(ctx context.Context, arg CreateBusinessClaimParams) (BusinessClaim, error) {
	row := q.db.QueryRow(ctx, createBusinessClaim, arg.BusinessID, arg.UserID, arg.Message)
	var i BusinessClaim
	err := row.Scan(
		&i.ID,
		&i.BusinessID,
		&i.UserID,
		&i.Message,
		&i.Status,
		&i.CreatedAt,
		&i.ResolvedAt,
	)
	return i, err
}

const getBusinessClaim = `-- name: GetBusinessClaim :one
SELECT id, business_id, user_id, message, status, created_at, resolved_at FROM business_claims WHERE id = $1
`

func (q *Queries) GetBusinessClaim(ctx context.Context, id pgtype.UUID) (BusinessClaim, error) {
	row := q.db.QueryRow(ctx, getBusinessClaim, id)
	var i BusinessClaim
	err := row.Scan(
		&i.ID,
		&i.BusinessID,
		&i.UserID,
		&i.Message,
		&i.Status,
		&i.CreatedAt,
		&i.ResolvedAt,
	)
	return i, err
}

const listBusinessClaims = `-- name: ListBusinessClaims :many
SELECT
    bc.id, bc.business_id, bc.user_id, bc.message, bc.status, bc.created_at, bc.resolved_at,
    b.name AS business_name, b.slug AS business_slug, u.email AS user_email
FROM business_claims bc
JOIN businesses b ON b.id = bc.business_id
JOIN users u ON u.id = bc.user_id
WHERE ($1::text IS NULL OR bc.status = $1)
  AND ($2::uuid IS NULL OR bc.user_id = $2)
ORDER BY bc.created_at DESC
`

type ListBusinessClaimsParams struct {
	Status *string     `json:"status"`
	UserID pgtype.UUID `json:"user_id"`
}

type ListBusinessClaimsRow struct {
	ID           pgtype.UUID        `json:"id"`
	BusinessID   pgtype.UUID        `json:"business_id"`
	UserID       pgtype.UUID        `json:"user_id"`
	Message      *string            `json:"message"`
	Status       string             `json:"status"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	ResolvedAt   pgtype.Timestamptz `json:"resolved_at"`
	BusinessName string             `json:"business_name"`
	BusinessSlug string             `json:"business_slug"`
	UserEmail    string             `json:"user_email"`
}

func (q *Queries) ListBusinessClaims(ctx context.Context, arg ListBusinessClaimsParams) ([]ListBusinessClaimsRow, error) {
	rows, err := q.db.Query(ctx, listBusinessClaims, arg.Status, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListBusinessClaimsRow
	for rows.Next() {
		var i ListBusinessClaimsRow
		if err := rows.Scan(
			&i.ID,
			&i.BusinessID,
			&i.UserID,
			&i.Message,
			&i.Status,
			&i.CreatedAt,
			&i.ResolvedAt,
			&i.BusinessName,
			&i.BusinessSlug,
			&i.UserEmail,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const resolveBusinessClaim = `-- name: ResolveBusinessClaim :one
UPDATE business_claims SET status = $2, resolved_at = now() WHERE id = $1
RETURNING id, business_id, user_id, message, status, created_at, resolved_at
`

type ResolveBusinessClaimParams struct {
	ID     pgtype.UUID `json:"id"`
	Status string      `json:"status"`
}

func (q *Queries) ResolveBusinessClaim(ctx context.Context, arg ResolveBusinessClaimParams) (BusinessClaim, error) {
	row := q.db.QueryRow(ctx, resolveBusinessClaim, arg.ID, arg.Status)
	var i BusinessClaim
	err := row.Scan(
		&i.ID,
		&i.BusinessID,
		&i.UserID,
		&i.Message,
		&i.Status,
		&i.CreatedAt,
		&i.ResolvedAt,
	)
	return i, err
}
