// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: businesses.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createBusiness = `-- name: CreateBusiness :one
INSERT INTO businesses (
    name, slug, type, subtype, barrio, lat, lng, image, tags, description,
    hours, price_hint, price_typical_note, phone, web, email, instagram, verified
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18
)
RETURNING id, name, slug, type, subtype, barrio, lat, lng, image, tags, description, hours, price_hint, price_typical_note, phone, web, email, instagram, owner_id, verified, created_at, updated_at
`

type CreateBusinessParams struct {
	Name             string   `json:"name"`
	Slug             string   `json:"slug"`
	Type             string   `json:"type"`
	Subtype          string   `json:"subtype"`
	Barrio           string   `json:"barrio"`
	Lat              float64  `json:"lat"`
	Lng              float64  `json:"lng"`
	Image            string   `json:"image"`
	Tags             []string `json:"tags"`
	Description      string   `json:"description"`
	Hours            *string  `json:"hours"`
	PriceHint        *string  `json:"price_hint"`
	PriceTypicalNote *string  `json:"price_typical_note"`
	Phone            *string  `json:"phone"`
	Web              *string  `json:"web"`
	Email            *string  `json:"email"`
	Instagram        *string  `json:"instagram"`
	Verified         bool     `json:"verified"`
}

func (q *Queries) CreateBusiness(ctx context.Context, arg CreateBusinessParams) (Business, error) {
	row := q.db.QueryRow(ctx, createBusiness,
		arg.Name,
		arg.Slug,
		arg.Type,
		arg.Subtype,
		arg.Barrio,
		arg.Lat,
		arg.Lng,
		arg.Image,
		arg.Tags,
		arg.Description,
		arg.Hours,
		arg.PriceHint,
		arg.PriceTypicalNote,
		arg.Phone,
		arg.Web,
		arg.Email,
		arg.Instagram,
		arg.Verified,
	)
	var i Business
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Type,
		&i.Subtype,
		&i.Barrio,
		&i.Lat,
		&i.Lng,
		&i.Image,
		&i.Tags,
		&i.Description,
		&i.Hours,
		&i.PriceHint,
		&i.PriceTypicalNote,
		&i.Phone,
		&i.Web,
		&i.Email,
		&i.Instagram,
		&i.OwnerID,
		&i.Verified,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteBusiness = `-- name: DeleteBusiness :exec
DELETE FROM businesses WHERE id = $1
`

func (q *Queries) DeleteBusiness(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteBusiness, id)
	return err
}

const getBusinessByID = `-- name: GetBusinessByID :one
SELECT id, name, slug, type, subtype, barrio, lat, lng, image, tags, description, hours, price_hint, price_typical_note, phone, web, email, instagram, owner_id, verified, created_at, updated_at FROM businesses WHERE id = $1
`

func (q *Queries) GetBusinessByID(ctx context.Context, id pgtype.UUID) (Business, error) {
	row := q.db.QueryRow(ctx, getBusinessByID, id)
	var i Business
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Type,
		&i.Subtype,
		&i.Barrio,
		&i.Lat,
		&i.Lng,
		&i.Image,
		&i.Tags,
		&i.Description,
		&i.Hours,
		&i.PriceHint,
		&i.PriceTypicalNote,
		&i.Phone,
		&i.Web,
		&i.Email,
		&i.Instagram,
		&i.OwnerID,
		&i.Verified,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getBusinessBySlug = `-- name: GetBusinessBySlug :one
SELECT id, name, slug, type, subtype, barrio, lat, lng, image, tags, description, hours, price_hint, price_typical_note, phone, web, email, instagram, owner_id, verified, created_at, updated_at FROM businesses WHERE slug = $1
`

func (q *Queries) GetBusinessBySlug(ctx context.Context, slug string) (Business, error) {
	row := q.db.QueryRow(ctx, getBusinessBySlug, slug)
	var i Business
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Type,
		&i.Subtype,
		&i.Barrio,
		&i.Lat,
		&i.Lng,
		&i.Image,
		&i.Tags,
		&i.Description,
		&i.Hours,
		&i.PriceHint,
		&i.PriceTypicalNote,
		&i.Phone,
		&i.Web,
		&i.Email,
		&i.Instagram,
		&i.OwnerID,
		&i.Verified,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listBusinesses = `-- name: ListBusinesses :many
SELECT id, name, slug, type, subtype, barrio, lat, lng, image, tags, description, hours, price_hint, price_typical_note, phone, web, email, instagram, owner_id, verified, created_at, updated_at FROM businesses
WHERE ($1::text IS NULL OR type = $1)
  AND ($2::text IS NULL OR barrio = $2)
  AND ($3::text IS NULL OR name ILIKE '%' || $3 || '%')
ORDER BY name
`

type ListBusinessesParams struct {
	Type   *string `json:"type"`
	Barrio *string `json:"barrio"`
	Q      *string `json:"q"`
}

func (q *Queries) ListBusinesses(ctx context.Context, arg ListBusinessesParams) ([]Business, error) {
	rows, err := q.db.Query(ctx, listBusinesses, arg.Type, arg.Barrio, arg.Q)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Business
	for rows.Next() {
		var i Business
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.Type,
			&i.Subtype,
			&i.Barrio,
			&i.Lat,
			&i.Lng,
			&i.Image,
			&i.Tags,
			&i.Description,
			&i.Hours,
			&i.PriceHint,
			&i.PriceTypicalNote,
			&i.Phone,
			&i.Web,
			&i.Email,
			&i.Instagram,
			&i.OwnerID,
			&i.Verified,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBusinessesByOwner = `-- name: ListBusinessesByOwner :many
SELECT id, name, slug, type, subtype, barrio, lat, lng, image, tags, description, hours, price_hint, price_typical_note, phone, web, email, instagram, owner_id, verified, created_at, updated_at FROM businesses WHERE owner_id = $1 ORDER BY name
`

func (q *Queries) ListBusinessesByOwner(ctx context.Context, ownerID pgtype.UUID) ([]Business, error) {
	rows, err := q.db.Query(ctx, listBusinessesByOwner, ownerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Business
	for rows.Next() {
		var i Business
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.Type,
			&i.Subtype,
			&i.Barrio,
			&i.Lat,
			&i.Lng,
			&i.Image,
			&i.Tags,
			&i.Description,
			&i.Hours,
			&i.PriceHint,
			&i.PriceTypicalNote,
			&i.Phone,
			&i.Web,
			&i.Email,
			&i.Instagram,
			&i.OwnerID,
			&i.Verified,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setBusinessOwner = `-- name: SetBusinessOwner :one
UPDATE businesses SET owner_id = $2, updated_at = now() WHERE id = $1 RETURNING id, name, slug, type, subtype, barrio, lat, lng, image, tags, description, hours, price_hint, price_typical_note, phone, web, email, instagram, owner_id, verified, created_at, updated_at
`

type SetBusinessOwnerParams struct {
	ID      pgtype.UUID `json:"id"`
	OwnerID pgtype.UUID `json:"owner_id"`
}

func (q *Queries) SetBusinessOwner(ctx context.Context, arg SetBusinessOwnerParams) (Business, error) {
	row := q.db.QueryRow(ctx, setBusinessOwner, arg.ID, arg.OwnerID)
	var i Business
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Type,
		&i.Subtype,
		&i.Barrio,
		&i.Lat,
		&i.Lng,
		&i.Image,
		&i.Tags,
		&i.Description,
		&i.Hours,
		&i.PriceHint,
		&i.PriceTypicalNote,
		&i.Phone,
		&i.Web,
		&i.Email,
		&i.Instagram,
		&i.OwnerID,
		&i.Verified,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateBusiness = `-- name: UpdateBusiness :one
UPDATE businesses SET
    name = $2, slug = $3, type = $4, subtype = $5, barrio = $6, lat = $7, lng = $8,
    image = $9, tags = $10, description = $11, hours = $12, price_hint = $13,
    price_typical_note = $14, phone = $15, web = $16, email = $17, instagram = $18,
    verified = $19, updated_at = now()
WHERE id = $1
RETURNING id, name, slug, type, subtype, barrio, lat, lng, image, tags, description, hours, price_hint, price_typical_note, phone, web, email, instagram, owner_id, verified, created_at, updated_at
`

type UpdateBusinessParams struct {
	ID               pgtype.UUID `json:"id"`
	Name             string      `json:"name"`
	Slug             string      `json:"slug"`
	Type             string      `json:"type"`
	Subtype          string      `json:"subtype"`
	Barrio           string      `json:"barrio"`
	Lat              float64     `json:"lat"`
	Lng              float64     `json:"lng"`
	Image            string      `json:"image"`
	Tags             []string    `json:"tags"`
	Description      string      `json:"description"`
	Hours            *string     `json:"hours"`
	PriceHint        *string     `json:"price_hint"`
	PriceTypicalNote *string     `json:"price_typical_note"`
	Phone            *string     `json:"phone"`
	Web              *string     `json:"web"`
	Email            *string     `json:"email"`
	Instagram        *string     `json:"instagram"`
	Verified         bool        `json:"verified"`
}

func (q *Queries) UpdateBusiness(ctx context.Context, arg UpdateBusinessParams) (Business, error) {
	row := q.db.QueryRow(ctx, updateBusiness,
		arg.ID,
		arg.Name,
		arg.Slug,
		arg.Type,
		arg.Subtype,
		arg.Barrio,
		arg.Lat,
		arg.Lng,
		arg.Image,
		arg.Tags,
		arg.Description,
		arg.Hours,
		arg.PriceHint,
		arg.PriceTypicalNote,
		arg.Phone,
		arg.Web,
		arg.Email,
		arg.Instagram,
		arg.Verified,
	)
	var i Business
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Type,
		&i.Subtype,
		&i.Barrio,
		&i.Lat,
		&i.Lng,
		&i.Image,
		&i.Tags,
		&i.Description,
		&i.Hours,
		&i.PriceHint,
		&i.PriceTypicalNote,
		&i.Phone,
		&i.Web,
		&i.Email,
		&i.Instagram,
		&i.OwnerID,
		&i.Verified,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
