// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: events.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createEvent = `-- name: CreateEvent :one
INSERT INTO events (
    title, title_en, slug, start_date, end_date, type, venue, related_business_id,
    lat, lng, image, tags, description, description_en, content
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15
)
RETURNING id, title, slug, start_date, end_date, type, venue, related_business_id, lat, lng, image, tags, description, content, created_at, updated_at, title_en, description_en
`

type CreateEventParams struct {
	Title             string      `json:"title"`
	TitleEn           *string     `json:"title_en"`
	Slug              string      `json:"slug"`
	StartDate         pgtype.Date `json:"start_date"`
	EndDate           pgtype.Date `json:"end_date"`
	Type              string      `json:"type"`
	Venue             string      `json:"venue"`
	RelatedBusinessID pgtype.UUID `json:"related_business_id"`
	Lat               float64     `json:"lat"`
	Lng               float64     `json:"lng"`
	Image             string      `json:"image"`
	Tags              []string    `json:"tags"`
	Description       string      `json:"description"`
	DescriptionEn     *string     `json:"description_en"`
	Content           *string     `json:"content"`
}

func (q *Queries) CreateEvent(ctx context.Context, arg CreateEventParams) (Event, error) {
	row := q.db.QueryRow(ctx, createEvent,
		arg.Title,
		arg.TitleEn,
		arg.Slug,
		arg.StartDate,
		arg.EndDate,
		arg.Type,
		arg.Venue,
		arg.RelatedBusinessID,
		arg.Lat,
		arg.Lng,
		arg.Image,
		arg.Tags,
		arg.Description,
		arg.DescriptionEn,
		arg.Content,
	)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Slug,
		&i.StartDate,
		&i.EndDate,
		&i.Type,
		&i.Venue,
		&i.RelatedBusinessID,
		&i.Lat,
		&i.Lng,
		&i.Image,
		&i.Tags,
		&i.Description,
		&i.Content,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TitleEn,
		&i.DescriptionEn,
	)
	return i, err
}

const deleteEvent = `-- name: DeleteEvent :exec
DELETE FROM events WHERE id = $1
`

func (q *Queries) DeleteEvent(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteEvent, id)
	return err
}

const getEventBySlug = `-- name: GetEventBySlug :one
SELECT id, title, slug, start_date, end_date, type, venue, related_business_id, lat, lng, image, tags, description, content, created_at, updated_at, title_en, description_en FROM events WHERE slug = $1
`

func (q *Queries) GetEventBySlug(ctx context.Context, slug string) (Event, error) {
	row := q.db.QueryRow(ctx, getEventBySlug, slug)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Slug,
		&i.StartDate,
		&i.EndDate,
		&i.Type,
		&i.Venue,
		&i.RelatedBusinessID,
		&i.Lat,
		&i.Lng,
		&i.Image,
		&i.Tags,
		&i.Description,
		&i.Content,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TitleEn,
		&i.DescriptionEn,
	)
	return i, err
}

const listEvents = `-- name: ListEvents :many
SELECT id, title, slug, start_date, end_date, type, venue, related_business_id, lat, lng, image, tags, description, content, created_at, updated_at, title_en, description_en FROM events ORDER BY start_date
`

func (q *Queries) ListEvents(ctx context.Context) ([]Event, error) {
	rows, err := q.db.Query(ctx, listEvents)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Event
	for rows.Next() {
		var i Event
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Slug,
			&i.StartDate,
			&i.EndDate,
			&i.Type,
			&i.Venue,
			&i.RelatedBusinessID,
			&i.Lat,
			&i.Lng,
			&i.Image,
			&i.Tags,
			&i.Description,
			&i.Content,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.TitleEn,
			&i.DescriptionEn,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateEvent = `-- name: UpdateEvent :one
UPDATE events SET
    title = $2, title_en = $3, slug = $4, start_date = $5, end_date = $6, type = $7, venue = $8,
    lat = $9, lng = $10, image = $11, tags = $12, description = $13, description_en = $14, content = $15,
    updated_at = now()
WHERE id = $1
RETURNING id, title, slug, start_date, end_date, type, venue, related_business_id, lat, lng, image, tags, description, content, created_at, updated_at, title_en, description_en
`

type UpdateEventParams struct {
	ID            pgtype.UUID `json:"id"`
	Title         string      `json:"title"`
	TitleEn       *string     `json:"title_en"`
	Slug          string      `json:"slug"`
	StartDate     pgtype.Date `json:"start_date"`
	EndDate       pgtype.Date `json:"end_date"`
	Type          string      `json:"type"`
	Venue         string      `json:"venue"`
	Lat           float64     `json:"lat"`
	Lng           float64     `json:"lng"`
	Image         string      `json:"image"`
	Tags          []string    `json:"tags"`
	Description   string      `json:"description"`
	DescriptionEn *string     `json:"description_en"`
	Content       *string     `json:"content"`
}

func (q *Queries) UpdateEvent(ctx context.Context, arg UpdateEventParams) (Event, error) {
	row := q.db.QueryRow(ctx, updateEvent,
		arg.ID,
		arg.Title,
		arg.TitleEn,
		arg.Slug,
		arg.StartDate,
		arg.EndDate,
		arg.Type,
		arg.Venue,
		arg.Lat,
		arg.Lng,
		arg.Image,
		arg.Tags,
		arg.Description,
		arg.DescriptionEn,
		arg.Content,
	)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Slug,
		&i.StartDate,
		&i.EndDate,
		&i.Type,
		&i.Venue,
		&i.RelatedBusinessID,
		&i.Lat,
		&i.Lng,
		&i.Image,
		&i.Tags,
		&i.Description,
		&i.Content,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TitleEn,
		&i.DescriptionEn,
	)
	return i, err
}
