// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: favorites.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addFavorite = `-- name: AddFavorite :exec
INSERT INTO user_favorites (user_id, business_id) VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

type AddFavoriteParams struct {
	UserID     pgtype.UUID `json:"user_id"`
	BusinessID pgtype.UUID `json:"business_id"`
}

func (q *Queries) AddFavorite(ctx context.Context, arg AddFavoriteParams) error {
	_, err := q.db.Exec(ctx, addFavorite, arg.UserID, arg.BusinessID)
	return err
}

const listFavoriteBusinesses = `-- name: ListFavoriteBusinesses :many
SELECT b.id, b.name, b.slug, b.type, b.subtype, b.barrio, b.lat, b.lng, b.image, b.tags, b.description, b.hours, b.price_hint, b.price_typical_note, b.phone, b.web, b.email, b.instagram, b.owner_id, b.verified, b.created_at, b.updated_at FROM businesses b
JOIN user_favorites f ON f.business_id = b.id
WHERE f.user_id = $1
ORDER BY f.created_at DESC
`

func (q *Queries) ListFavoriteBusinesses(ctx context.Context, userID pgtype.UUID) ([]Business, error) {
	rows, err := q.db.Query(ctx, listFavoriteBusinesses, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Business
	for rows.Next() {
		var i Business
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.Type,
			&i.Subtype,
			&i.Barrio,
			&i.Lat,
			&i.Lng,
			&i.Image,
			&i.Tags,
			&i.Description,
			&i.Hours,
			&i.PriceHint,
			&i.PriceTypicalNote,
			&i.Phone,
			&i.Web,
			&i.Email,
			&i.Instagram,
			&i.OwnerID,
			&i.Verified,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeFavorite = `-- name: RemoveFavorite :exec
DELETE FROM user_favorites WHERE user_id = $1 AND business_id = $2
`

type RemoveFavoriteParams struct {
	UserID     pgtype.UUID `json:"user_id"`
	BusinessID pgtype.UUID `json:"business_id"`
}

func (q *Queries) RemoveFavorite(ctx context.Context, arg RemoveFavoriteParams) error {
	_, err := q.db.Exec(ctx, removeFavorite, arg.UserID, arg.BusinessID)
	return err
}
