// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Achievement struct {
	ID           pgtype.UUID        `json:"id"`
	Code         string             `json:"code"`
	Title        string             `json:"title"`
	Description  string             `json:"description"`
	Icon         string             `json:"icon"`
	CriteriaType string             `json:"criteria_type"`
	Threshold    int32              `json:"threshold"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

type Business struct {
	ID               pgtype.UUID        `json:"id"`
	Name             string             `json:"name"`
	Slug             string             `json:"slug"`
	Type             string             `json:"type"`
	Subtype          string             `json:"subtype"`
	Barrio           string             `json:"barrio"`
	Lat              float64            `json:"lat"`
	Lng              float64            `json:"lng"`
	Image            string             `json:"image"`
	Tags             []string           `json:"tags"`
	Description      string             `json:"description"`
	Hours            *string            `json:"hours"`
	PriceHint        *string            `json:"price_hint"`
	PriceTypicalNote *string            `json:"price_typical_note"`
	Phone            *string            `json:"phone"`
	Web              *string            `json:"web"`
	Email            *string            `json:"email"`
	Instagram        *string            `json:"instagram"`
	OwnerID          pgtype.UUID        `json:"owner_id"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
	DescriptionEn    *string            `json:"description_en"`
}

type BusinessClaim struct {
	ID         pgtype.UUID        `json:"id"`
	BusinessID pgtype.UUID        `json:"business_id"`
	UserID     pgtype.UUID        `json:"user_id"`
	Message    *string            `json:"message"`
	Status     string             `json:"status"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	ResolvedAt pgtype.Timestamptz `json:"resolved_at"`
}

type Event struct {
	ID                pgtype.UUID        `json:"id"`
	Title             string             `json:"title"`
	Slug              string             `json:"slug"`
	StartDate         pgtype.Date        `json:"start_date"`
	EndDate           pgtype.Date        `json:"end_date"`
	Type              string             `json:"type"`
	Venue             string             `json:"venue"`
	RelatedBusinessID pgtype.UUID        `json:"related_business_id"`
	Lat               float64            `json:"lat"`
	Lng               float64            `json:"lng"`
	Image             string             `json:"image"`
	Tags              []string           `json:"tags"`
	Description       string             `json:"description"`
	Content           *string            `json:"content"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
	TitleEn           *string            `json:"title_en"`
	DescriptionEn     *string            `json:"description_en"`
}

type Parish struct {
	ID           pgtype.UUID `json:"id"`
	Name         string      `json:"name"`
	Address      string      `json:"address"`
	Neighborhood string      `json:"neighborhood"`
	Phone        *string     `json:"phone"`
}

type ParishSchedule struct {
	ID       pgtype.UUID `json:"id"`
	ParishID pgtype.UUID `json:"parish_id"`
	Day      string      `json:"day"`
	Times    []string    `json:"times"`
	Position int32       `json:"position"`
}

type Plan struct {
	ID           pgtype.UUID `json:"id"`
	Title        string      `json:"title"`
	Description  string      `json:"description"`
	Type         string      `json:"type"`
	Price        string      `json:"price"`
	PriceAmount  *string     `json:"price_amount"`
	Date         string      `json:"date"`
	Time         string      `json:"time"`
	Location     string      `json:"location"`
	Neighborhood string      `json:"neighborhood"`
}

type Route struct {
	ID            pgtype.UUID        `json:"id"`
	Slug          string             `json:"slug"`
	Title         string             `json:"title"`
	Description   string             `json:"description"`
	Duration      string             `json:"duration"`
	Distance      string             `json:"distance"`
	Difficulty    string             `json:"difficulty"`
	Category      string             `json:"category"`
	Image         string             `json:"image"`
	Highlights    []string           `json:"highlights"`
	AudioGuide    bool               `json:"audio_guide"`
	Offline       bool               `json:"offline"`
	Price         string             `json:"price"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
	TitleEn       *string            `json:"title_en"`
	DescriptionEn *string            `json:"description_en"`
}

type RouteStep struct {
	ID          pgtype.UUID `json:"id"`
	RouteID     pgtype.UUID `json:"route_id"`
	Title       string      `json:"title"`
	Description string      `json:"description"`
	AudioUrl    *string     `json:"audio_url"`
	Duration    *string     `json:"duration"`
	Lat         *float64    `json:"lat"`
	Lng         *float64    `json:"lng"`
	Image       *string     `json:"image"`
	Position    int32       `json:"position"`
}

type User struct {
	ID           pgtype.UUID        `json:"id"`
	Email        string             `json:"email"`
	PasswordHash string             `json:"password_hash"`
	Role         string             `json:"role"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

type UserFavorite struct {
	UserID     pgtype.UUID        `json:"user_id"`
	BusinessID pgtype.UUID        `json:"business_id"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type UserRouteProgress struct {
	UserID      pgtype.UUID        `json:"user_id"`
	RouteID     pgtype.UUID        `json:"route_id"`
	CurrentStep int32              `json:"current_step"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}
