// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: parishes.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createParish = `-- name: CreateParish :one
INSERT INTO parishes (name, address, neighborhood, phone)
VALUES ($1, $2, $3, $4)
RETURNING id, name, address, neighborhood, phone
`

type CreateParishParams struct {
	Name         string  `json:"name"`
	Address      string  `json:"address"`
	Neighborhood string  `json:"neighborhood"`
	Phone        *string `json:"phone"`
}

func (q *Queries) CreateParish(ctx context.Context, arg CreateParishParams) (Parish, error) {
	row := q.db.QueryRow(ctx, createParish,
		arg.Name,
		arg.Address,
		arg.Neighborhood,
		arg.Phone,
	)
	var i Parish
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Address,
		&i.Neighborhood,
		&i.Phone,
	)
	return i, err
}

const createParishSchedule = `-- name: CreateParishSchedule :one
INSERT INTO parish_schedules (parish_id, day, times, position)
VALUES ($1, $2, $3, $4)
RETURNING id, parish_id, day, times, position
`

type CreateParishScheduleParams struct {
	ParishID pgtype.UUID `json:"parish_id"`
	Day      string      `json:"day"`
	Times    []string    `json:"times"`
	Position int32       `json:"position"`
}

func (q *Queries) CreateParishSchedule(ctx context.Context, arg CreateParishScheduleParams) (ParishSchedule, error) {
	row := q.db.QueryRow(ctx, createParishSchedule,
		arg.ParishID,
		arg.Day,
		arg.Times,
		arg.Position,
	)
	var i ParishSchedule
	err := row.Scan(
		&i.ID,
		&i.ParishID,
		&i.Day,
		&i.Times,
		&i.Position,
	)
	return i, err
}

const deleteParish = `-- name: DeleteParish :exec
DELETE FROM parishes WHERE id = $1
`

func (q *Queries) DeleteParish(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteParish, id)
	return err
}

const deleteSchedulesByParish = `-- name: DeleteSchedulesByParish :exec
DELETE FROM parish_schedules WHERE parish_id = $1
`

func (q *Queries) DeleteSchedulesByParish(ctx context.Context, parishID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteSchedulesByParish, parishID)
	return err
}

const listParishes = `-- name: ListParishes :many
SELECT id, name, address, neighborhood, phone FROM parishes ORDER BY name
`

func (q *Queries) ListParishes(ctx context.Context) ([]Parish, error) {
	rows, err := q.db.Query(ctx, listParishes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Parish
	for rows.Next() {
		var i Parish
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Address,
			&i.Neighborhood,
			&i.Phone,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSchedulesByParish = `-- name: ListSchedulesByParish :many
SELECT id, parish_id, day, times, position FROM parish_schedules WHERE parish_id = $1 ORDER BY position
`

func (q *Queries) ListSchedulesByParish(ctx context.Context, parishID pgtype.UUID) ([]ParishSchedule, error) {
	rows, err := q.db.Query(ctx, listSchedulesByParish, parishID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ParishSchedule
	for rows.Next() {
		var i ParishSchedule
		if err := rows.Scan(
			&i.ID,
			&i.ParishID,
			&i.Day,
			&i.Times,
			&i.Position,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateParish = `-- name: UpdateParish :one
UPDATE parishes SET name = $2, address = $3, neighborhood = $4, phone = $5
WHERE id = $1
RETURNING id, name, address, neighborhood, phone
`

type UpdateParishParams struct {
	ID           pgtype.UUID `json:"id"`
	Name         string      `json:"name"`
	Address      string      `json:"address"`
	Neighborhood string      `json:"neighborhood"`
	Phone        *string     `json:"phone"`
}

func (q *Queries) UpdateParish(ctx context.Context, arg UpdateParishParams) (Parish, error) {
	row := q.db.QueryRow(ctx, updateParish,
		arg.ID,
		arg.Name,
		arg.Address,
		arg.Neighborhood,
		arg.Phone,
	)
	var i Parish
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Address,
		&i.Neighborhood,
		&i.Phone,
	)
	return i, err
}
