// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: plans.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createPlan = `-- name: CreatePlan :one
INSERT INTO plans (title, description, type, price, price_amount, date, time, location, neighborhood)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, title, description, type, price, price_amount, date, time, location, neighborhood
`

type CreatePlanParams struct {
	Title        string  `json:"title"`
	Description  string  `json:"description"`
	Type         string  `json:"type"`
	Price        string  `json:"price"`
	PriceAmount  *string `json:"price_amount"`
	Date         string  `json:"date"`
	Time         string  `json:"time"`
	Location     string  `json:"location"`
	Neighborhood string  `json:"neighborhood"`
}

func (q *Queries) CreatePlan(ctx context.Context, arg CreatePlanParams) (Plan, error) {
	row := q.db.QueryRow(ctx, createPlan,
		arg.Title,
		arg.Description,
		arg.Type,
		arg.Price,
		arg.PriceAmount,
		arg.Date,
		arg.Time,
		arg.Location,
		arg.Neighborhood,
	)
	var i Plan
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.Type,
		&i.Price,
		&i.PriceAmount,
		&i.Date,
		&i.Time,
		&i.Location,
		&i.Neighborhood,
	)
	return i, err
}

const deletePlan = `-- name: DeletePlan :exec
DELETE FROM plans WHERE id = $1
`

func (q *Queries) DeletePlan(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deletePlan, id)
	return err
}

const listPlans = `-- name: ListPlans :many
SELECT id, title, description, type, price, price_amount, date, time, location, neighborhood FROM plans ORDER BY title
`

func (q *Queries) ListPlans(ctx context.Context) ([]Plan, error) {
	rows, err := q.db.Query(ctx, listPlans)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Plan
	for rows.Next() {
		var i Plan
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.Type,
			&i.Price,
			&i.PriceAmount,
			&i.Date,
			&i.Time,
			&i.Location,
			&i.Neighborhood,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePlan = `-- name: UpdatePlan :one
UPDATE plans SET
    title = $2, description = $3, type = $4, price = $5, price_amount = $6,
    date = $7, time = $8, location = $9, neighborhood = $10
WHERE id = $1
RETURNING id, title, description, type, price, price_amount, date, time, location, neighborhood
`

type UpdatePlanParams struct {
	ID           pgtype.UUID `json:"id"`
	Title        string      `json:"title"`
	Description  string      `json:"description"`
	Type         string      `json:"type"`
	Price        string      `json:"price"`
	PriceAmount  *string     `json:"price_amount"`
	Date         string      `json:"date"`
	Time         string      `json:"time"`
	Location     string      `json:"location"`
	Neighborhood string      `json:"neighborhood"`
}

func (q *Queries) UpdatePlan(ctx context.Context, arg UpdatePlanParams) (Plan, error) {
	row := q.db.QueryRow(ctx, updatePlan,
		arg.ID,
		arg.Title,
		arg.Description,
		arg.Type,
		arg.Price,
		arg.PriceAmount,
		arg.Date,
		arg.Time,
		arg.Location,
		arg.Neighborhood,
	)
	var i Plan
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.Type,
		&i.Price,
		&i.PriceAmount,
		&i.Date,
		&i.Time,
		&i.Location,
		&i.Neighborhood,
	)
	return i, err
}
