// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: route_progress.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countCompletedRoutes = `-- name: CountCompletedRoutes :one
SELECT count(*) FROM user_route_progress p
JOIN (
    SELECT route_id, count(*) AS total_steps FROM route_steps GROUP BY route_id
) s ON s.route_id = p.route_id
WHERE p.user_id = $1 AND p.current_step >= s.total_steps - 1
`

func (q *Queries) CountCompletedRoutes(ctx context.Context, userID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countCompletedRoutes, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getRouteProgress = `-- name: GetRouteProgress :one
SELECT user_id, route_id, current_step, updated_at FROM user_route_progress WHERE user_id = $1 AND route_id = $2
`

type GetRouteProgressParams struct {
	UserID  pgtype.UUID `json:"user_id"`
	RouteID pgtype.UUID `json:"route_id"`
}

func (q *Queries) GetRouteProgress(ctx context.Context, arg GetRouteProgressParams) (UserRouteProgress, error) {
	row := q.db.QueryRow(ctx, getRouteProgress, arg.UserID, arg.RouteID)
	var i UserRouteProgress
	err := row.Scan(
		&i.UserID,
		&i.RouteID,
		&i.CurrentStep,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertRouteProgress = `-- name: UpsertRouteProgress :one
INSERT INTO user_route_progress (user_id, route_id, current_step)
VALUES ($1, $2, $3)
ON CONFLICT (user_id, route_id)
DO UPDATE SET current_step = $3, updated_at = now()
RETURNING user_id, route_id, current_step, updated_at
`

type UpsertRouteProgressParams struct {
	UserID      pgtype.UUID `json:"user_id"`
	RouteID     pgtype.UUID `json:"route_id"`
	CurrentStep int32       `json:"current_step"`
}

func (q *Queries) UpsertRouteProgress(ctx context.Context, arg UpsertRouteProgressParams) (UserRouteProgress, error) {
	row := q.db.QueryRow(ctx, upsertRouteProgress, arg.UserID, arg.RouteID, arg.CurrentStep)
	var i UserRouteProgress
	err := row.Scan(
		&i.UserID,
		&i.RouteID,
		&i.CurrentStep,
		&i.UpdatedAt,
	)
	return i, err
}
