// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: routes.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createRoute = `-- name: CreateRoute :one
INSERT INTO routes (
    slug, title, description, duration, distance, difficulty, category, image,
    highlights, audio_guide, offline, price
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12
)
RETURNING id, slug, title, description, duration, distance, difficulty, category, image, highlights, audio_guide, offline, price, created_at, updated_at
`

type CreateRouteParams struct {
	Slug        string   `json:"slug"`
	Title       string   `json:"title"`
	Description string   `json:"description"`
	Duration    string   `json:"duration"`
	Distance    string   `json:"distance"`
	Difficulty  string   `json:"difficulty"`
	Category    string   `json:"category"`
	Image       string   `json:"image"`
	Highlights  []string `json:"highlights"`
	AudioGuide  bool     `json:"audio_guide"`
	Offline     bool     `json:"offline"`
	Price       string   `json:"price"`
}

func (q *Queries) CreateRoute(ctx context.Context, arg CreateRouteParams) (Route, error) {
	row := q.db.QueryRow(ctx, createRoute,
		arg.Slug,
		arg.Title,
		arg.Description,
		arg.Duration,
		arg.Distance,
		arg.Difficulty,
		arg.Category,
		arg.Image,
		arg.Highlights,
		arg.AudioGuide,
		arg.Offline,
		arg.Price,
	)
	var i Route
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Title,
		&i.Description,
		&i.Duration,
		&i.Distance,
		&i.Difficulty,
		&i.Category,
		&i.Image,
		&i.Highlights,
		&i.AudioGuide,
		&i.Offline,
		&i.Price,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createRouteStep = `-- name: CreateRouteStep :one
INSERT INTO route_steps (route_id, title, description, audio_url, duration, lat, lng, image, position)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, route_id, title, description, audio_url, duration, lat, lng, image, position
`

type CreateRouteStepParams struct {
	RouteID     pgtype.UUID `json:"route_id"`
	Title       string      `json:"title"`
	Description string      `json:"description"`
	AudioUrl    *string     `json:"audio_url"`
	Duration    *string     `json:"duration"`
	Lat         *float64    `json:"lat"`
	Lng         *float64    `json:"lng"`
	Image       *string     `json:"image"`
	Position    int32       `json:"position"`
}

func (q *Queries) CreateRouteStep(ctx context.Context, arg CreateRouteStepParams) (RouteStep, error) {
	row := q.db.QueryRow(ctx, createRouteStep,
		arg.RouteID,
		arg.Title,
		arg.Description,
		arg.AudioUrl,
		arg.Duration,
		arg.Lat,
		arg.Lng,
		arg.Image,
		arg.Position,
	)
	var i RouteStep
	err := row.Scan(
		&i.ID,
		&i.RouteID,
		&i.Title,
		&i.Description,
		&i.AudioUrl,
		&i.Duration,
		&i.Lat,
		&i.Lng,
		&i.Image,
		&i.Position,
	)
	return i, err
}

const deleteRoute = `-- name: DeleteRoute :exec
DELETE FROM routes WHERE id = $1
`

func (q *Queries) DeleteRoute(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteRoute, id)
	return err
}

const deleteStepsByRoute = `-- name: DeleteStepsByRoute :exec
DELETE FROM route_steps WHERE route_id = $1
`

func (q *Queries) DeleteStepsByRoute(ctx context.Context, routeID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteStepsByRoute, routeID)
	return err
}

const getRouteBySlug = `-- name: GetRouteBySlug :one
SELECT id, slug, title, description, duration, distance, difficulty, category, image, highlights, audio_guide, offline, price, created_at, updated_at FROM routes WHERE slug = $1
`

func (q *Queries) GetRouteBySlug(ctx context.Context, slug string) (Route, error) {
	row := q.db.QueryRow(ctx, getRouteBySlug, slug)
	var i Route
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Title,
		&i.Description,
		&i.Duration,
		&i.Distance,
		&i.Difficulty,
		&i.Category,
		&i.Image,
		&i.Highlights,
		&i.AudioGuide,
		&i.Offline,
		&i.Price,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listRoutes = `-- name: ListRoutes :many
SELECT id, slug, title, description, duration, distance, difficulty, category, image, highlights, audio_guide, offline, price, created_at, updated_at FROM routes ORDER BY title
`

func (q *Queries) ListRoutes(ctx context.Context) ([]Route, error) {
	rows, err := q.db.Query(ctx, listRoutes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Route
	for rows.Next() {
		var i Route
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Title,
			&i.Description,
			&i.Duration,
			&i.Distance,
			&i.Difficulty,
			&i.Category,
			&i.Image,
			&i.Highlights,
			&i.AudioGuide,
			&i.Offline,
			&i.Price,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStepsByRoute = `-- name: ListStepsByRoute :many
SELECT id, route_id, title, description, audio_url, duration, lat, lng, image, position FROM route_steps WHERE route_id = $1 ORDER BY position
`

func (q *Queries) ListStepsByRoute(ctx context.Context, routeID pgtype.UUID) ([]RouteStep, error) {
	rows, err := q.db.Query(ctx, listStepsByRoute, routeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RouteStep
	for rows.Next() {
		var i RouteStep
		if err := rows.Scan(
			&i.ID,
			&i.RouteID,
			&i.Title,
			&i.Description,
			&i.AudioUrl,
			&i.Duration,
			&i.Lat,
			&i.Lng,
			&i.Image,
			&i.Position,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateRoute = `-- name: UpdateRoute :one
UPDATE routes SET
    slug = $2, title = $3, description = $4, duration = $5, distance = $6,
    difficulty = $7, category = $8, image = $9, highlights = $10,
    audio_guide = $11, offline = $12, price = $13, updated_at = now()
WHERE id = $1
RETURNING id, slug, title, description, duration, distance, difficulty, category, image, highlights, audio_guide, offline, price, created_at, updated_at
`

type UpdateRouteParams struct {
	ID          pgtype.UUID `json:"id"`
	Slug        string      `json:"slug"`
	Title       string      `json:"title"`
	Description string      `json:"description"`
	Duration    string      `json:"duration"`
	Distance    string      `json:"distance"`
	Difficulty  string      `json:"difficulty"`
	Category    string      `json:"category"`
	Image       string      `json:"image"`
	Highlights  []string    `json:"highlights"`
	AudioGuide  bool        `json:"audio_guide"`
	Offline     bool        `json:"offline"`
	Price       string      `json:"price"`
}

func (q *Queries) UpdateRoute(ctx context.Context, arg UpdateRouteParams) (Route, error) {
	row := q.db.QueryRow(ctx, updateRoute,
		arg.ID,
		arg.Slug,
		arg.Title,
		arg.Description,
		arg.Duration,
		arg.Distance,
		arg.Difficulty,
		arg.Category,
		arg.Image,
		arg.Highlights,
		arg.AudioGuide,
		arg.Offline,
		arg.Price,
	)
	var i Route
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Title,
		&i.Description,
		&i.Duration,
		&i.Distance,
		&i.Difficulty,
		&i.Category,
		&i.Image,
		&i.Highlights,
		&i.AudioGuide,
		&i.Offline,
		&i.Price,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
